product_demos/Data-Science/chatbot-rag-llm/01-quickstart/01-Data-Preparation-and-Index.py, product_demos/Data-Science/chatbot-rag-llm/01-quickstart/02-Deploy-RAG-Chatbot-Model.py, product_demos/Data-Science/chatbot-rag-llm/02-advanced/01-PDF-Advanced-Data-Preparation.py, product_demos/Data-Science/chatbot-rag-llm/02-advanced/02-Advanced-Chatbot-Chain.py, product_demos/Data-Science/chatbot-rag-llm/02-advanced/03-Offline-Evaluation.py, product_demos/Data-Science/chatbot-rag-llm/02-advanced/04-Deploy-Model-as-Endpoint.py, product_demos/Data-Science/chatbot-rag-llm/02-advanced/05-Inference-Tables-Analysis-Notebook-with-LLM-Metrics.py, product_demos/Data-Science/chatbot-rag-llm/_resources/00-init-advanced.py, product_demos/Data-Science/chatbot-rag-llm/_resources/00-init.py
- Upgrade langchain version to 0.1.5
- Upgrade mlflow version to 2.10.1
- Don't use dataframe_split API when querying the chain model
=> Upgrade langchain and mlflow version

product_demos/Unity-Catalog/uc-01-acl/01-Row-Column-access-control.sql
Primary fix was to ensure that all queries that are supposed to return results (which is all the queries) actually return results.
This was fixed by ensuring proper group membership.
Additionally, several improvements to wording for comments were introduced.
Thanks to Dennis Shultz (Sr Solutions Architect, Databricks) and Mohan Mathews (Sr Delivery Solutions Architect, Databricks) for testing and editing.
=> revamped UC demo for fine grained access controls

product_demos/Data-Science/computer-vision-dl/00-introduction-deep-learning-vision.py, product_demos/Data-Science/computer-vision-dl/01-ingestion-and-ETL.py, product_demos/Data-Science/computer-vision-dl/02-huggingface-model-training.py, product_demos/Data-Science/computer-vision-dl/03-running-cv-inferences.py, product_demos/Data-Science/computer-vision-dl/05-torch-lightning-training-and-inference.py
Some typo fixes I made as I went along the demo.
=> typo fixes

product_demos/Data-Science/feature-store/01_Feature_store_introduction.py, product_demos/Data-Science/feature-store/02_Feature_store_advanced.py
Fix a markdown typo and correct the information concerning the fe.write_table mode option.
=> Minor documentation only changes

product_demos/Data-Science/chatbot-rag-llm/01-quickstart/02-Deploy-RAG-Chatbot-Model.py
Vector Search in NB1 configured with embedding model, so not needed at retrieval step. Extension of https://github.com/databricks-demos/dbdemos-notebooks/pull/17
=> Removing extraneous embedding_model code

product_demos/Data-Science/chatbot-rag-llm/_resources/02-lakehouse-app-helpers.py
=> LakehouseAppHelper: update delete API

product_demos/Data-Science/chatbot-rag-llm/03-advanced-app/02-Advanced-Chatbot-Chain.py
deploy_model() is outdated.
Closes #30
=> databricks agents: fix deploy method

product_demos/DBSQL-Datawarehousing/lakehouse-monitor/01-Timeseries-monitor.py, product_demos/DBSQL-Datawarehousing/lakehouse-monitor/_resources/01-DataGeneration.py
There is a bug in the LHM demo where it pushes nulls to array of list, causing error:
```
Can not merge type `ArrayType` and `DoubleType`.
```
Also made few changes:
1. Uncomment SLICING_EXPRS
2. Check if drift table exists
=> fix lhm where code is pushing nulls to array of list

demo-HLS/lakehouse-patient-readmission/01-Data-Ingestion/01.1-DLT-patient-readmission-SQL.sql
created empty string to resolve issue with null values in drug_exposure schema
=> corrected null values in drug_exposure schema

demo-FSI/lakehouse-fsi-fraud-detection/_resources/00-setup.py
Missing data condition updated to customer, transactions and fraud-transaction folders. 
Wait time added before processing parquet files.
=> Missing data condition updated and wait time added

product_demos/Unity-Catalog/uc-04-system-tables/_enable_system_tables.py
Consolidated code to use python sdk and workspace client for auth and to enable system tables
=> system tables auth and code cleanup

product_demos/Data-Science/mlops-end2end/02-mlops-advanced/00_mlops_end2end_advanced.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/01_feature_engineering.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/02_automl_champion.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/03_from_notebook_to_models_in_uc.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/04_challenger_validation.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/05_batch_inference.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/06_serve_features_and_model.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/07_model_monitoring.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/08_drift_detection.py
Minor updates to point all images to reference dbdemos-resources instead of our forks.
=> Changed image paths to dbdemos-resources

product_demos/Data-Science/mlops-end2end/02-mlops-advanced/00_mlops_end2end_advanced.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/01_feature_engineering.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/02_automl_champion.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/03_from_notebook_to_models_in_uc.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/04_challenger_validation.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/05_batch_inference.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/06_serve_features_and_model.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/07_model_monitoring.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/08_drift_detection.py
- fixed some typos and md
- fixed broken links
- code clean and trim
=> [MLOps3.0] Final review of advanced demo

product_demos/Data-Science/llm-tools-functions/advanced-tool-examples/04-summit-cookie-demo.py
This is the first revision of the cookie notebook. It's super simple: Two functions are created, and an agent runs them. The data has a manual installation step through the marketplace until we get a marketplace API.
Next steps are to add VS lookup and image gen.
=> adding v0 cookie notebook

product_demos/DBSQL-Datawarehousing/lakehouse-monitor/_resources/01-DataGeneration.py
Most transformations in data generation script were rewritten from pandas to Spark to capture lineage as per documentation Queries must use Spark DataFrames to capture lineage correctly: https://docs.databricks.com/en/data-governance/unity-catalog/data-lineage.html
Additionally one more gold table was added which includes the Preferred Payment and Payment column to show impacted gold layer tables in the demo.
=> Adjust transformations to fix lineage

product_demos/DBSQL-Datawarehousing/lakehouse-monitor/_resources/01-DataGeneration.py
* Cleaned code
* Fixed minor bug for lineage
=> [LHM] Minor bug fixes and code cleaning

product_demos/DBSQL-Datawarehousing/lakehouse-monitor/_resources/01-DataGeneration.py
=> [LHM] Cleaned/Homogenized invoking pyspark functions

aibi/aibi-supply-chain-forecasting/AI-BI-Supply-chain.py, aibi/aibi-supply-chain-forecasting/_resources/bundle_config.py, aibi/aibi-supply-chain-forecasting/_resources/dashboards/supply-chain.lvdash.json
Added Supply Chain Optimization AIBI demo
=> Add MFG App

demo-FSI/lakehouse-fsi-smart-claims/00-Smart-Claims-Introduction.py
Fix broken claims process diagram link
Before:
After:
=> Fix 00-Smart-Claims-Introduction.py claims process diagram

aibi/aibi-marketing-campaign/_resources/bundle_config.py, aibi/aibi-patient-genomics/_resources/bundle_config.py, aibi/aibi-portfolio-assistant/_resources/bundle_config.py, aibi/aibi-sales-pipeline-review/_resources/bundle_config.py, aibi/aibi-supply-chain-forecasting/_resources/bundle_config.py
=> Change bundle file -- remove / from AIBI

aibi/aibi-marketing-campaign/_resources/bundle_config.py, aibi/aibi-portfolio-assistant/_resources/bundle_config.py, aibi/aibi-portfolio-assistant/_resources/dashboards/portfolio-assistant.lvdash.json, aibi/aibi-supply-chain-forecasting/_resources/bundle_config.py, aibi/aibi-supply-chain-forecasting/_resources/dashboards/supply-chain.lvdash.json
Big changes to MFG, FINS, marketing, and HLS demos
=> Clean-up aibi demos before publish!

product_demos/DBSQL-Datawarehousing/lakehouse-monitor/_resources/01-DataGeneration.py
Please test properly on different DBRs.
=> Fix Lineage

product_demos/Data-Science/mlops-end2end/_resources/bundle_config.py
Hi Quentin,
I added an init_demo block in the bundle config.
It should init both the quickstart and the advanced demo.
Please check.
Chia-Yui
=> Added init_demo block in bundle config

product_demos/Data-Science/feature-store/01_Feature_store_introduction.py, product_demos/Data-Science/feature-store/02_Feature_store_advanced.py, product_demos/Data-Science/feature-store/03_Feature_store_expert.py
Adding dataset logging to the three Feature Store demo notebooks.
=> Adding Dataset Logging to the Feature Store notebooks

product_demos/Delta-Live-Table/dlt-cdc/02-Retail_DLT_CDC_Python.py, product_demos/Delta-Live-Table/dlt-cdc/04-Retail_DLT_CDC_Full.py, product_demos/Delta-Live-Table/dlt-loans/02-DLT-Loan-pipeline-PYTHON.py
More small tested tweaks to [DLT Syntax](https://github.com/databricks-demos/dbdemos-notebooks/pull/85). Thanks @QuentinAmbard.
=> DLT Syntax: Follow-up

demo-retail/lakehouse-retail-c360/01-Data-ingestion/01.1-DLT-churn-SQL.sql, demo-retail/lakehouse-retail-c360/01-Data-ingestion/01.2-DLT-churn-Python-UDF.py, demo-retail/lakehouse-retail-c360/01-Data-ingestion/01.3-DLT-churn-python.py, demo-retail/lakehouse-retail-c360/01-Data-ingestion/plain-spark-delta-pipeline/01.5-Delta-pipeline-spark-churn.py, demo-retail/lakehouse-retail-c360/02-Data-governance/02-UC-data-governance-security-churn.sql, demo-retail/lakehouse-retail-c360/04-Data-Science-ML/04.1-automl-churn-prediction.py, demo-retail/lakehouse-retail-c360/04-Data-Science-ML/04.2-automl-generated-notebook.py, demo-retail/lakehouse-retail-c360/04-Data-Science-ML/04.3-running-inference.py, demo-retail/lakehouse-retail-c360/_resources/00-setup.py, demo-retail/lakehouse-retail-c360/_resources/01-load-data.py, demo-retail/lakehouse-retail-c360/_resources/bundle_config.py
update our demo to work in serverless - still requires DBR16 for full udf support
=> lakehouse retail demo compatible for serverless

product_demos/Unity-Catalog/uc-04-system-tables/01-billing-tables/02-forecast-billing-tables.py, product_demos/dbt-on-databricks/_resources/bundle_config.py
package addition and clause for serverless added to dbt and uc-system tables billing demos
=> Small fixes

product_demos/Data-Science/chatbot-rag-llm/01-first-step/00-Mosaic-AI-Agent-Demo.py, product_demos/Data-Science/chatbot-rag-llm/01-first-step/01-First-Step-RAG-On-Databricks.py, product_demos/Data-Science/chatbot-rag-llm/02-simple-app/01-Data-Preparation-and-Index.py, product_demos/Data-Science/chatbot-rag-llm/02-simple-app/02-Deploy-RAG-Chatbot-Model.py
Currently, some links are not working.
I found that some links were missing the $ symbol, so I added it to them
=> add $ to enable a link

demo-FSI/lakehouse-fsi-credit-decisioning/01-Data-Ingestion/01-DLT-Internal-Banking-Data-SQL.sql, demo-FSI/lakehouse-fsi-credit-decisioning/_resources/bundle_config.py
- Modify the DLT query for funds_trans_gold table
- Add Genie room
=> Fix FSI Credit Decisioning demo

demo-FSI/lakehouse-fsi-credit-decisioning/01-Data-Ingestion/01-DLT-Internal-Banking-Data-SQL.sql, demo-FSI/lakehouse-fsi-credit-decisioning/_resources/bundle_config.py
Reverts databricks-demos/dbdemos-notebooks#105
=> Revert "Fix FSI Credit Decisioning demo" for now

demo-FSI/lakehouse-fsi-credit-decisioning/01-Data-Ingestion/01-DLT-Internal-Banking-Data-SQL.sql, demo-FSI/lakehouse-fsi-credit-decisioning/_resources/bundle_config.py
Reverts databricks-demos/dbdemos-notebooks#118
=> Re-revert "Revert "Fix FSI Credit Decisioning demo" for now"

demo-FSI/lakehouse-fsi-credit-decisioning/03-Data-Science-ML/03.1-Feature-Engineering-credit-decisioning.py
Reverts databricks-demos/dbdemos-notebooks#120
=> Revert "Slight modification to credit-decisioning demo"

demo-retail/lakehouse-retail-c360/05-Generative-AI/05.1-Agent-Functions-Creation.ipynb
- Churn Prediction function
- Customer Order Lookup function
- Personalized Marketing Copy function
=> Add genAI functions for Retail C360 demo

product_demos/DBSQL-Datawarehousing/sql-ai-functions/00-SQL-AI-Functions-Introduction.py, product_demos/DBSQL-Datawarehousing/sql-ai-functions/02-Generate-fake-data-with-AI-functions.sql
I added a couple of updates:
- A description in the introduction notebook on Serverless (provisionless) capability
- A note in the 02-Generate-fake-data-with-AI-functions on Query Profile UI.
=> Updated with addition information

demo-retail/lakehouse-retail-c360/01-Data-ingestion/01.2-DLT-churn-Python-UDF.py, demo-retail/lakehouse-retail-c360/01-Data-ingestion/01.3-DLT-churn-python.py, demo-retail/lakehouse-retail-c360/01-Data-ingestion/01.4-DLT-churn-expectation-dashboard-data-prep.sql, demo-retail/lakehouse-retail-c360/01-Data-ingestion/plain-spark-delta-pipeline/01.5-Delta-pipeline-spark-churn.py, demo-retail/lakehouse-retail-c360/04-Data-Science-ML/04.1-automl-churn-prediction.py, demo-retail/lakehouse-retail-c360/04-Data-Science-ML/04.2-automl-generated-notebook.py, demo-retail/lakehouse-retail-c360/04-Data-Science-ML/04.3-running-inference.py, demo-retail/lakehouse-retail-c360/_resources/01-load-data.py
+ Replace the event_log for DLT
=> Bump mlflow version of lakehouse retail

product_demos/Delta-Live-Table/dlt-loans/02-DLT-Loan-pipeline-PYTHON.py, product_demos/delta-sharing-airlines/01-Delta-Sharing-presentation.py, product_demos/delta-sharing-airlines/02-provider-delta-sharing-demo.sql, product_demos/delta-sharing-airlines/03-receiver-delta-sharing-demo.py, product_demos/delta-sharing-airlines/04-share-data-within-databricks.sql, product_demos/delta-sharing-airlines/05-extra-delta-sharing-rest-api.py
=> fix: correct typos

product_demos/streaming-sessionization/_00-Delta-session-PRODUCER.py, product_demos/streaming-sessionization/_resources/bundle_config.py
Changes to the security and port settings of the PRODUCER notebook to fix current issues.
Related DB Internal slack thread: https://databricks.slack.com/archives/C02GZJSLAR0/p1744739197334869
=> Fixes to PRODUCER notebook of STREAMING SESSIONIZATION demo

product_demos/Delta-Live-Table/declarative-pipelines/00-Lakeflow-Declarative-Pipeline-Introduction.py, product_demos/Delta-Live-Table/declarative-pipelines/_resources/01-Bike-Data-generator.py, product_demos/Delta-Live-Table/declarative-pipelines/explorations/01-Exploring-the-Data.py, product_demos/Delta-Live-Table/declarative-pipelines/transformations/00-pipeline-tutorial.py, product_demos/Delta-Live-Table/declarative-pipelines/transformations/01-bronze.sql, product_demos/Delta-Live-Table/declarative-pipelines/transformations/02-silver.sql
Data Generator (01-Bike-Data-generator.py)
Added customer CDC schema with 2000 records (800 members + 1200 non-members)
Implemented realistic CDC sequences: APPEND (100%), UPDATE (10% of customers), DELETE (3% of customers with UPDATEs)
Generated Parquet files partitioned by date
Bronze Layer (01-bronze.sql)
Added CUSTOMERS_CDC_RAW streaming table for Parquet ingestion
Silver Layer (02-silver.sql)
Created customers_cdc_clean with data quality constraints
Implemented Auto CDC flows with both SCD Type 1 and SCD Type 2
Generated customers table (SCD Type 1) and customers_history table (SCD Type 2) via Auto CDC
Data Exploration (01-Exploring-the-Data.py)
Added customer CDC data exploration section
Included operation distribution analysis
📝 Documentation Updates
Main Introduction …
=> "customers" flow added to declarative_pipeline demo "pipeline-bike"

product_demos/auto-loader/01-Auto-loader-schema-evolution-Ingestion.py
Incremental listing option is changed to deprecated and the notification system option is changed for the recommended one.
=> Align Auto Loader notebook with official docs

product_demos/metric_view/metric_view_demo/[Step1]_metric_view_with_assistant.sql, product_demos/metric_view/metric_view_demo/[Step2]_metric_view_with_sql.sql, product_demos/metric_view/metric_view_demo/[Step3]_use_metric_view_in_genie.sql, product_demos/metric_view/metric_view_demo/[Step4]_use_metric_view_in_dashboard.sql, product_demos/metric_view/metric_view_demo/[Step5]_use_metric_view_in_sql.sql
https://databricks.atlassian.net/browse/FEIP-1125
=> Demo for Metric Views

product_demos/Data-Science/mlops-end2end/02-mlops-advanced/02_model_training_hpo_optuna.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/03a_create_deployment_job.py, product_demos/Data-Science/mlops-end2end/02-mlops-advanced/04b_challenger_approval.py
- Decreased `n_jobs` to 2 for HPO/AutoML to avoid risk of error
- Update MLflow deployment job creation notebook to check for model and job existence first
- Added default values for validation tasks
=> [MLOps3.0] Minor fixes
